---
openapi: 3.0.0
info:
  title: Workers API
  description: Workers collection API to manage worker's profiles.
  version: "1"
servers:
- url: https://virtserver.swaggerhub.com/PAPAIOPROG_1/lab-1/1
  description: Mock Server
- url: https://api.papaio.xyz
  description: Production
paths:
  /workers:
    get:
      tags:
      - worker
      summary: List all workers
      description: Lists all workers page by page
      operationId: list
      parameters:
      - name: offset
        in: query
        description: The number of items to skip before starting to collect the result set.
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
      - name: limit
        in: query
        description: The numbers of items to return.
        required: false
        style: form
        explode: true
        schema:
          maximum: 10
          minimum: 1
          type: integer
          default: 5
      - name: filterName
        in: query
        description: Fields for sorting
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: showAvgSalary
        in: query
        description: Fields for sorting
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: showTotalSalary
        in: query
        description: Fields for sorting
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: sort
        in: query
        description: Fields for sorting
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            minItems: 1
            type: string
            enum:
            - id asc
            - name asc
            - coordinates.x asc
            - coordinates.y asc
            - creationDate asc
            - salary asc
            - endDate asc
            - position asc
            - status asc
            - birthday asc
            - weight asc
            - passportId asc
            - id desc
            - name desc
            - coordinates.x desc
            - coordinates.y desc
            - creationDate desc
            - salary desc
            - endDate desc
            - position desc
            - status desc
            - birthday desc
            - weight desc
            - passportId desc
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              example:
                sumSalary: 10000000
                averageSalary: 340000
                result:
                - id: 1
                  name: Bob Smith
                  salary: 340000.5
                  endDate: Sun Oct 16 2022 20:51:11 GMT+0300
                  position: ENGINEER
                  status: REGULAR
                  person:
                    birthday: Sun Oct 16 1982 20:51:11 GMT+0300
                    weight: 53.9
                    passportID: XD051870267
                - id: 2
                  name: Jessica Smith
                  salary: 340000.5
                  endDate: Sun Oct 16 2022 20:51:11 GMT+0300
                  position: ENGINEER
                  status: REGULAR
                  person:
                    birthday: Sun Oct 16 1982 20:51:11 GMT+0300
                    weight: 53.9
                    passportID: XD051870267
                - id: 3
                  name: Arnold James
                  salary: 340000.5
                  endDate: Sun Oct 16 2022 20:51:11 GMT+0300
                  position: ENGINEER
                  status: REGULAR
                  person:
                    birthday: Sun Oct 16 1982 20:51:11 GMT+0300
                    weight: 53.9
                    passportID: XD051870267
                - id: 4
                  name: Andrew Lincoln
                  salary: 340000.5
                  endDate: Sun Oct 16 2022 20:51:11 GMT+0300
                  position: ENGINEER
                  status: REGULAR
                  person:
                    birthday: Sun Oct 16 1982 20:51:11 GMT+0300
                    weight: 53.9
                    passportID: XD051870267
                - id: 5
                  name: Pablo Escobar
                  salary: 340000.5
                  endDate: Sun Oct 16 2022 20:51:11 GMT+0300
                  position: ENGINEER
                  status: REGULAR
                  person:
                    birthday: Sun Oct 16 1982 20:51:11 GMT+0300
                    weight: 53.9
                    passportID: XD051870267
                - id: 6
                  name: Angela Watermelon
                  salary: 340000.5
                  endDate: Sun Oct 16 2022 20:51:11 GMT+0300
                  position: ENGINEER
                  status: REGULAR
                  person:
                    birthday: Sun Oct 16 1982 20:51:11 GMT+0300
                    weight: 53.9
                    passportID: XD051870267
                - id: 7
                  name: James James
                  salary: 340000.5
                  endDate: Sun Oct 16 2022 20:51:11 GMT+0300
                  position: ENGINEER
                  status: REGULAR
                  person:
                    birthday: Sun Oct 16 1982 20:51:11 GMT+0300
                    weight: 53.9
                    passportID: XD051870267
                - id: 8
                  name: Arnold Ashley
                  salary: 340000.5
                  endDate: Sun Oct 16 2022 20:51:11 GMT+0300
                  position: ENGINEER
                  status: REGULAR
                  person:
                    birthday: Sun Oct 16 1982 20:51:11 GMT+0300
                    weight: 53.9
                    passportID: XD051870267
                - id: 9
                  name: George Xi
                  salary: 340000.5
                  endDate: Sun Oct 16 2022 20:51:11 GMT+0300
                  position: ENGINEER
                  status: REGULAR
                  person:
                    birthday: Sun Oct 16 1982 20:51:11 GMT+0300
                    weight: 53.9
                    passportID: XD051870267
                - id: 10
                  name: Alex Porche
                  salary: 340000.5
                  endDate: Sun Oct 16 2022 20:51:11 GMT+0300
                  position: ENGINEER
                  status: REGULAR
                  person:
                    birthday: Sun Oct 16 1982 20:51:11 GMT+0300
                    weight: 53.9
                    passportID: XD051870267
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
      - worker
      summary: Create worker
      description: Creates worker and returns it
      operationId: addWorker
      requestBody:
        $ref: '#/components/requestBodies/Worker'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /workers/{id}:
    get:
      tags:
      - worker
      summary: Find specific worker
      description: Returns specific user by id
      operationId: findWorker
      parameters:
      - name: id
        in: path
        description: The user ID.
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
      - worker
      summary: Delete worker
      description: Deletes worker by id
      operationId: deleteWorker
      parameters:
      - name: id
        in: path
        description: The user ID.
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
      - worker
      summary: Update worker
      description: Updates worker by id
      operationId: updateWorker
      parameters:
      - name: id
        in: path
        description: The user ID.
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        $ref: '#/components/requestBodies/Worker'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "501":
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /workers/sort-params/:
    get:
      tags:
      - utils
      summary: List all worker's sort params
      description: List all worker's sort params as array
      operationId: listSortParams
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
              example:
                sortBy:
                - id
                - name
                - coordinates.x
                - coordinates.y
                - creationDate
                - salary
                - endDate
                - position
                - status
                - birthday
                - weight
                - passportId
                orderBy:
                - asc
                - desc
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          example: Error
    Success:
      type: object
      properties:
        message:
          type: string
          example: Success
    Person:
      type: object
      properties:
        birthday:
          type: string
          format: date-time
        weight:
          type: number
          format: float
          example: 84.4
        passportID:
          type: string
          example: XN001939020
    Coordinates:
      type: object
      properties:
        x:
          type: integer
          format: int64
          example: 437
        y:
          type: number
          format: double
          example: 92.7
    Worker:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Bob Brown
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date
        salary:
          type: number
          format: double
          example: 340000.5
        endDate:
          type: string
          format: date-time
        position:
          type: string
          example: DEVELOPER
          enum:
          - ENGINEER
          - DEVELOPER
          - BAKER
        status:
          type: string
          example: HIRED
          enum:
          - FIRED
          - HIRED
          - REGULAR
        person:
          $ref: '#/components/schemas/Person'
    inline_response_200:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/Worker'
        sum:
          type: number
          format: int64
    inline_response_200_1:
      type: object
      properties:
        result:
          type: array
          items:
            type: string
  parameters:
    offsetParam:
      name: offset
      in: query
      description: The number of items to skip before starting to collect the result set.
      required: false
      style: form
      explode: true
      schema:
        minimum: 0
        type: integer
    limitParam:
      name: limit
      in: query
      description: The numbers of items to return.
      required: false
      style: form
      explode: true
      schema:
        maximum: 10
        minimum: 1
        type: integer
        default: 5
  requestBodies:
    Worker:
      description: Worker object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Worker'
